### PR TITLE
Snapdragon: fix after move to SDK3.0

### PR DESCRIPTION
**Pull request by julianoes**
This fixes some changes which came with the change to SDK3.0 and didn't get caught with #169.

### CODE REVIEW

**Comment by julianoes** [comment]
Looks like I was wrong, don't merge yet.

**Comment by julianoes** [comment]
@LorenzMeier can you port this to the new Devguide please?

**Comment by LorenzMeier** [comment]
yep!

**Comment by LorenzMeier** [comment]
Merged.

**Comment by julianoes** [comment]
Cool, thanks.

**Pull request closed without merging**
