### PR TITLE
simulation-gazebo: go from version 6 to 7 on Linux

### PR DESCRIPTION
**Pull request by julianoes**
These instructions work on Ubuntu 15.10. 

In my setup, I have ROS compiled from source, so I'm not sure if/how this would work together with ROS from deps.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
According to these instructions it doesn't work:
http://dev.px4.io/simulation-ros-interface.html

Which ROS version are you sporting? The question is if we can run ROS Jade with its default Gazebo version just fine, which is what we should recommend then:
http://dev.px4.io/simulation-ros-interface.html

**Comment by LorenzMeier** [comment]
@vilhjalmur89 Could you help to clarify if we can use ROS Jade by default?

**Comment by julianoes** [comment]
@LorenzMeier should we port this over as well?

**Comment by LorenzMeier** [comment]
Eventually yes, but need clarity on ROS version first.

**Comment by julianoes** [comment]
Bump: 7 is fine right? :)

**Comment by julianoes** [comment]
I've tested ROS Kinetic and Gazebo 7 with MAVROS on Ubuntu 16.04 without troubles.

**Comment by julianoes** [comment]
Replaced by https://github.com/PX4/Devguide/pull/17.

**Pull request closed without merging**
